-- Active: 1725459846237@@127.0.0.1@5432@tienda3
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clientes
(
    id serial NOT NULL,
    nombre text,
    ap_paterno text,
    direccion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id serial NOT NULL,
    nombre text,
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tipo_transaciones
(
    id serial NOT NULL,
    nombre text NOT NULL,
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transaciones
(
    id serial NOT NULL,
    id_cliente integer NOT NULL,
    id_producto integer NOT NULL,
    id_tipo_transacion integer NOT NULL,
    fecha date NOT NULL,
    precio float NOT NULL,
    cantidad integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.transaciones
    ADD FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaciones
    ADD FOREIGN KEY (id_producto)
    REFERENCES public.productos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transaciones
    ADD FOREIGN KEY (id_tipo_transacion)
    REFERENCES public.tipo_transaciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;