-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.libros
(
    id serial NOT NULL,
    titulo text NOT NULL,
    autor text NOT NULL,
    "ISBN" character(11) NOT NULL,
    publicacion integer,
    PRIMARY KEY (id)
);
END;