-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.estudiante
(
    id_estudiante serial NOT NULL,
    nombre text,
    apellido text,
    fecha_nacimiento date,
    PRIMARY KEY (id_estudiante)
);

CREATE TABLE IF NOT EXISTS public.curso
(
    id_curso serial NOT NULL,
    nombre_curso text,
    costo float,
    PRIMARY KEY (id_curso)
);

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pago serial NOT NULL,
    id_estudiante serial,
    monto float,
    fecha_pago date,
    metodo_pago text,
    id_curso serial,
    PRIMARY KEY (id_pago)
);

ALTER TABLE IF EXISTS public.pago
    ADD FOREIGN KEY (id_estudiante)
    REFERENCES public.estudiante (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pago
    ADD FOREIGN KEY (id_curso)
    REFERENCES public.curso (id_curso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;